@startuml
skinparam linestyle ortho
rectangle "Host Computer" as HC
rectangle "Host Computer Software" as HSC
rectangle "Database" as DB
rectangle "Web Browser" as WB
DB -right-> HSC : "Select all entries"
HC -down-> DB : "Provide the file to be viewed and analyzed"
HSC -> HSC : "Analyze data from disk"
HSC -down-> WB : "Serve homepage from data"
@enduml
