@startuml
!pragma useVerticalIf on
start
:Start-up;
if(Diagnostic Routine) then (No Errors)
:Continue with Application;
else (Errors)
:Shutdown;
stop
endif
:U.I loads Preview Screen;
repeat
:Show Preview Screen;
if(Study Button pressed) then (yes)
 :U.I shows Study Profile Selection Screen;
 :Select Study Profile;
 :U.I shows Live preview of cameras and sensors information;
 
(no) elseif (Menu List Screen button pressed) then (yes)
if(Change ISO) then (Yes)
 :U.I shows ISO adjusting screen;
 (no) elseif(Change Aperture Size) then (Yes)
 :U.I shows Aperture Size adjusting screen;
 (no) elseif(Change Shutter Speed) then (Yes)
 :U.I shows Shutter Speed adjusting screen;
 (no) elseif(Change whiteBalance) then (Yes)
 :U.I shows whiteBalance adjusting screen;
(no) elseif (Calibrate sensors) then (yes)
:U.I shows sensors calibration screens;
else (no)
 endif
(no) elseif(Capture button pressed) is (yes)
:Start Study Capture;
 :Data is backed up into Database;
else (no)
endif
repeat while (Button not pressed) is (yes)
@endum
