@startuml
package "Host Software"  {
	frame "Study Profile" #AQUA
	[Entry Preview] #LAWNGREEN
	[Database Preview] #GOLD
	
}
package "File System" {
	database SQLite
	folder "Raspberry Pi Backup" {
		[Study Media]
	}
}
[Raspberry Pi]
"Host Software" <-left-> "Raspberry Pi"
"Host Software" <-up-> "File System"
@enduml
