@startuml
package "Host Software"  {
	frame "Study Profile" #AQUA
	[Entry Preview] #LAWNGREEN
	[Database Preview] #GOLD
	
}
package "File System" {
		[Study Media]
}
[Raspberry Pi]
"Host Software" <-left-> "Raspberry Pi"
"Host Software" <-right-> "File System"
@enduml
